### ISSUE TITLE
Issue with gam-merge: ***glibc detected***

### ISSUE THREAD

**Issue by skyvic234** [vice87/gam-ngs#13]
My run of gam-merge terminated with errors of "**\* glibc detected **\* /backup/Gene/wbjiao/usr/gam-ngs/bin/gam-merge: free(): invalid". Ran the test data set through and worked fine. I have no idea why it happens. Here is the debugging output. Can you give me some clues on how to fix the bug? Thank you.

[main] Loading blocks
[main] Loaded blocks = 382
[main] Loading BAMs data
[bam] Master PE-alignments file soap.txt successfully opened:
      /backup/Gene/ssun/MH/S2_block/merge/chr01/1/short.srt.bam
         inserts size = 273.199 +/- 36.545  coverage = 75.9661
[bam] Slave PE-alignments file masu.txt successfully opened:
      /backup/Gene/ssun/MH/S2_block/merge/chr01/1/masu.short.srt.bam
         inserts size = 273.432 +/- 36.5705 coverage = 78.0621
[main] Loading contigs data
**\* glibc detected **\* /backup/Gene/wbjiao/usr/gam-ngs/bin/gam-merge: free(): invalid next size (fast): 0x0000000000f4b1e0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3d9747174f]
/lib64/libc.so.6(cfree+0x4b)[0x3d97475a4b]
/backup/Gene/wbjiao/usr/gam-ngs/bin/gam-merge(_Z18getNoBlocksContigsRKSt6vectorI11reference_tSaIS0_EES4_RKSt4listI5BlockSaIS6_EERSt3setIiSt4lessIiESaIiEESG_+0x625)[0x460a15]
/backup/Gene/wbjiao/usr/gam-ngs/bin/gam-merge(_ZN7modules5Merge7executeEv+0x1510)[0x4395b0]
/backup/Gene/wbjiao/usr/gam-ngs/bin/gam-merge(main+0x2f)[0x437e4f]
/lib64/libc.so.6(__libc_start_main+0xf4)[0x3d9741d9c4]
/backup/Gene/wbjiao/usr/gam-ngs/bin/gam-merge(__gxx_personality_v0+0x199)[0x436bc9]
======= Memory map: ========
00400000-00500000 r-xp 00000000 00:18 1124997048                         /backup/Gene/wbjiao/usr/gam-ngs/bin/gam-merge
00700000-00702000 rw-p 00100000 00:18 1124997048                         /backup/Gene/wbjiao/usr/gam-ngs/bin/gam-merge
00702000-00703000 rw-p 00702000 00:00 0 
00f0b000-00fc1000 rw-p 00f0b000 00:00 0                                  [heap]
3d97000000-3d9701c000 r-xp 00000000 08:03 49217862                       /lib64/ld-2.5.so
3d9721c000-3d9721d000 r--p 0001c000 08:03 49217862                       /lib64/ld-2.5.so
3d9721d000-3d9721e000 rw-p 0001d000 08:03 49217862                       /lib64/ld-2.5.so
3d97400000-3d9754f000 r-xp 00000000 08:03 49217863                       /lib64/libc-2.5.so
3d9754f000-3d9774f000 ---p 0014f000 08:03 49217863                       /lib64/libc-2.5.so
3d9774f000-3d97753000 r--p 0014f000 08:03 49217863                       /lib64/libc-2.5.so
3d97753000-3d97754000 rw-p 00153000 08:03 49217863                       /lib64/libc-2.5.so
3d97754000-3d97759000 rw-p 3d97754000 00:00 0 
3d97c00000-3d97c16000 r-xp 00000000 08:03 49217869                       /lib64/libpthread-2.5.so
3d97c16000-3d97e16000 ---p 00016000 08:03 49217869                       /lib64/libpthread-2.5.so
3d97e16000-3d97e17000 r--p 00016000 08:03 49217869                       /lib64/libpthread-2.5.so
3d97e17000-3d97e18000 rw-p 00017000 08:03 49217869                       /lib64/libpthread-2.5.so
3d97e18000-3d97e1c000 rw-p 3d97e18000 00:00 0 
3d98000000-3d98082000 r-xp 00000000 08:03 49217868                       /lib64/libm-2.5.so
3d98082000-3d98281000 ---p 00082000 08:03 49217868                       /lib64/libm-2.5.so
3d98281000-3d98282000 r--p 00081000 08:03 49217868                       /lib64/libm-2.5.so
3d98282000-3d98283000 rw-p 00082000 08:03 49217868                       /lib64/libm-2.5.so
3d98400000-3d98414000 r-xp 00000000 08:03 49217875                       /lib64/libz.so.1.2.3
3d98414000-3d98613000 ---p 00014000 08:03 49217875                       /lib64/libz.so.1.2.3
3d98613000-3d98614000 rw-p 00013000 08:03 49217875                       /lib64/libz.so.1.2.3
3d98800000-3d98807000 r-xp 00000000 08:03 49217870                       /lib64/librt-2.5.so
3d98807000-3d98a07000 ---p 00007000 08:03 49217870                       /lib64/librt-2.5.so
3d98a07000-3d98a08000 r--p 00007000 08:03 49217870                       /lib64/librt-2.5.so
3d98a08000-3d98a09000 rw-p 00008000 08:03 49217870                       /lib64/librt-2.5.so
3d99400000-3d9940d000 r-xp 00000000 08:03 49217866                       /lib64/libgcc_s-4.1.2-20080825.so.1
3d9940d000-3d9960d000 ---p 0000d000 08:03 49217866                       /lib64/libgcc_s-4.1.2-20080825.so.1
3d9960d000-3d9960e000 rw-p 0000d000 08:03 49217866                       /lib64/libgcc_s-4.1.2-20080825.so.1
2ad91dac6000-2ad91dac9000 rw-p 2ad91dac6000 00:00 0 
2ad91dac9000-2ad91db28000 r-xp 00000000 00:18 1126303879                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_graph.so.1.55.0
2ad91db28000-2ad91dd27000 ---p 0005f000 00:18 1126303879                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_graph.so.1.55.0
2ad91dd27000-2ad91dd2b000 rw-p 0005e000 00:18 1126303879                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_graph.so.1.55.0
2ad91dd2b000-2ad91dd92000 r-xp 00000000 00:18 1126304489                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_program_options.so.1.55.0
2ad91dd92000-2ad91df92000 ---p 00067000 00:18 1126304489                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_program_options.so.1.55.0
2ad91df92000-2ad91df96000 rw-p 00067000 00:18 1126304489                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_program_options.so.1.55.0
2ad91df96000-2ad91df97000 rw-p 2ad91df96000 00:00 0 
2ad91df97000-2ad91df9a000 r-xp 00000000 00:18 1126303596                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_system.so.1.55.0
2ad91df9a000-2ad91e199000 ---p 00003000 00:18 1126303596                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_system.so.1.55.0
2ad91e199000-2ad91e19a000 rw-p 00002000 00:18 1126303596                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_system.so.1.55.0
2ad91e19a000-2ad91e1af000 r-xp 00000000 00:18 1126303796                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_filesystem.so.1.55.0
2ad91e1af000-2ad91e3af000 ---p 00015000 00:18 1126303796                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_filesystem.so.1.55.0
2ad91e3af000-2ad91e3b0000 rw-p 00015000 00:18 1126303796                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_filesystem.so.1.55.0
2ad91e3b0000-2ad91e49a000 r-xp 00000000 00:18 1232866104                 /backup/Gene/local/gcc/lib64/libstdc++.so.6.0.17
2ad91e49a000-2ad91e699000 ---p 000ea000 00:18 1232866104                 /backup/Gene/local/gcc/lib64/libstdc++.so.6.0.17
2ad91e699000-2ad91e6a1000 r--p 000e9000 00:18 1232866104                 /backup/Gene/local/gcc/lib64/libstdc++.so.6.0.17
2ad91e6a1000-2ad91e6a3000 rw-p 000f1000 00:18 1232866104                 /backup/Gene/local/gcc/lib64/libstdc++.so.6.0.17
2ad91e6a3000-2ad91e6ba000 rw-p 2ad91e6a3000 00:00 0 
2ad91e6ba000-2ad91e7ab000 r-xp 00000000 00:18 1126303844                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_regex.so.1.55.0
2ad91e7ab000-2ad91e9aa000 ---p 000f1000 00:18 1126303844                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_regex.so.1.55.0
2ad91e9aa000-2ad91e9b0000 rw-p 000f0000 00:18 1126303844                 /backup/Gene/wbjiao/usr/boost1.55/lib/libboost_regex.so.1.55.0
2ad91e9b0000-2ad91edb4000 rw-p 2ad91e9b0000 00:00 0 
7fff85a12000-7fff85a28000 rw-p 7ffffffe8000 00:00 0                      [stack]
7fff85b63000-7fff85b66000 r-xp 7fff85b63000 00:00 0                      [vdso]
ffffffffff600000-ffffffffffe00000 ---p 00000000 00:00 0                  [vsyscall]
Aborted

**Comment by vice87** [comment]
This issue should have been fixed in the last release.
