### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by jakalssj3** [vice87/gam-ngs#20]
Hi, I'm getting an error while running gam-merge. The command I'm using to execute is:

gam-merge --blocks-file test_out.blocks --master-bam ABySS.PE.list.txt --master-fasta from_ABySS/genome_contigs.ABySS.fasta --slave-bam Sanger_phusion.PE.list.txt --slave-fasta from_Sanger/genome_contigs.Sanger_phusion.fasta --min-block-size 10 --output test_out --threads 8 >gam-merge.log.out 2>gam-merge.log.err 

File gam-merge.log.err is empty, gam-merge.log.out contains the following:

[main] Loading blocks
[main] Loaded blocks = 36329
[main] Loading BAMs data
[bam] Master PE-alignments file ABySS.PE.list.txt successfully opened:
      ./from_ABySS/ABySS.mapped.bwa.sorted.bam
         inserts size = 473.738 +/- 17.6493 coverage = 67.5435
[bam] Slave PE-alignments file Sanger_phusion.PE.list.txt successfully opened:
      ./from_Sanger/Sanger_phusion.mapped.bwa.sorted.bam
         inserts size = 472.653 +/- 19.0498 coverage = 90.1553
[main] Loading contigs data

Running gam-merge in debug mode (with single thread) gives the following output:

Starting program: /share3/home/seq-r/appl/marcin/GAM-NGS/gam-ngs-master_2/bin/gam-merge --blocks-file test_out.blocks --master-bam ABySS.PE.list.txt --master-fasta from_ABySS/genome_contigs.ABySS.fasta --slave-bam Sanger_phusion.PE.list.txt --slave-fasta from_Sanger/genome_contigs.Sanger_phusion.fasta --min-block-size 10 --output test_out --threads 1 >gam-merge.log.out 2>gam-merge.log.err
[Thread debugging using libthread_db enabled]

Program received signal SIGABRT, Aborted.
0x00007ffff65d28a5 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.80.el6_3.3.x86_64 zlib-1.2.3-25.el6.x86_64
#0  0x00007ffff65d28a5 in raise () from /lib64/libc.so.6
#1  0x00007ffff65d4085 in abort () from /lib64/libc.so.6
#2  0x00007ffff660fa97 in __libc_message () from /lib64/libc.so.6
#3  0x00007ffff66153c6 in malloc_printerr () from /lib64/libc.so.6
#4  0x00007ffff6618e44 in _int_malloc () from /lib64/libc.so.6
#5  0x00007ffff6619bf1 in malloc () from /lib64/libc.so.6
#6  0x00007ffff6e2a898 in operator new(unsigned long) () at ../../../../libstdc++-v3/libsupc++/new_op.cc:49
#7  0x000000000055cc93 in __gnu_cxx::new_allocatorstd::_Rb_tree_node<int >::allocate (this=0x7fffffffc140, __n=1) at /usr/lib/gcc/x86_64-redhat-linux/4.4.5/../../../../include/c++/4.4.5/ext/new_allocator.h:89
#8  0x000000000055ca60 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_get_node (this=0x7fffffffc140)

```
at /usr/lib/gcc/x86_64-redhat-linux/4.4.5/../../../../include/c++/4.4.5/bits/stl_tree.h:359
```
#9  0x000000000055c7dd in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_create_node(int const&) ()
#10 0x000000000055c3d3 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_insert_ (this=0x7fffffffc140, __x=0x0, __p=0x7fffffffc148, __v=@0x7fffffffb4fc)

```
at /usr/lib/gcc/x86_64-redhat-linux/4.4.5/../../../../include/c++/4.4.5/bits/stl_tree.h:881
```
#11 0x000000000055bab6 in std::_Rb_tree<int, int, std::_Identity<int>, std::less<int>, std::allocator<int> >::_M_insert_unique (this=0x7fffffffc140, __v=@0x7fffffffb4fc)

```
at /usr/lib/gcc/x86_64-redhat-linux/4.4.5/../../../../include/c++/4.4.5/bits/stl_tree.h:1177
```
#12 0x000000000055a987 in std::set<int, std::less<int>, std::allocator<int> >::insert (this=0x7fffffffc140, __x=@0x7fffffffb4fc)

```
at /usr/lib/gcc/x86_64-redhat-linux/4.4.5/../../../../include/c++/4.4.5/bits/stl_set.h:411
```
#13 0x000000000055923e in getNoBlocksContigs (masterRef=std::vector of length 57172, capacity 57172 = {...}, slaveRef=std::vector of length 4401, capacity 4401 = {...}, blocks=Traceback (most recent call last):

  File "/usr/local/package/gcc/gcc-4.9.0/lib64/../share/gcc-4.9.0/python/libstdcxx/v6/printers.py", line 114, in children
    nodetype = find_type(self.val.type, '_Node')
  File "/usr/local/package/gcc/gcc-4.9.0/lib64/../share/gcc-4.9.0/python/libstdcxx/v6/printers.py", line 52, in find_type
    field = typ.fields()[0]
IndexError: list index out of range
std::list, masterNBC=Traceback (most recent call last):
  File "/usr/local/package/gcc/gcc-4.9.0/lib64/../share/gcc-4.9.0/python/libstdcxx/v6/printers.py", line 477, in children
    rep_type = find_type(self.val.type, '_Rep_type')
  File "/usr/local/package/gcc/gcc-4.9.0/lib64/../share/gcc-4.9.0/python/libstdcxx/v6/printers.py", line 52, in find_type
    field = typ.fields()[0]
IndexError: list index out of range
std::set with 0 elements, slaveNBC=Traceback (most recent call last):
  File "/usr/local/package/gcc/gcc-4.9.0/lib64/../share/gcc-4.9.0/python/libstdcxx/v6/printers.py", line 477, in children
    rep_type = find_type(self.val.type, '_Rep_type')
  File "/usr/local/package/gcc/gcc-4.9.0/lib64/../share/gcc-4.9.0/python/libstdcxx/v6/printers.py", line 52, in find_type
    field = typ.fields()[0]
IndexError: list index out of range
std::set with 0 elements) at /home/seq-r/appl/marcin/GAM-NGS/gam-ngs-master_2/lib/src/assembly/Block.cc:855
#14 0x00000000005233ea in modules::Merge::execute (this=0x7fffffffc800) at /home/seq-r/appl/marcin/GAM-NGS/gam-ngs-master_2/src/Merge.cc:263
#15 0x0000000000521402 in main (argc=17, argv=0x7fffffffc918) at /home/seq-r/appl/marcin/GAM-NGS/gam-ngs-master_2/src/gam-merge.cc:49

A debugging session is active.

```
Inferior 1 [process 122493] will be killed.
```

**Comment by vice87** [comment]
The issue has been fixed in the last release.
