### ISSUE TITLE
Searching for Boost Libraries in /usr/lib64/lib64/

### ISSUE THREAD

**Issue by paudano** [vice87/gam-ngs#22]
The build process is looking for:
/usr/lib64/lib64/libboost_graph-mt.so.5

The file does not exist because of the extra "lib" in the path.

$ file /usr/lib64/libboost_graph-mt.so.5
/usr/lib64/libboost_graph-mt.so.5: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, stripped

Why would it be searching in /usr/lib64/lib64? Is there 

I get the same error when trying to specify the boost library location.
cmake -DBOOST_ROOT=/usr/lib64 ..

Session (output shown for cmake and make):

$ git clone https://github.com/vice87/gam-ngs.git
$ cd gam-ngs/
$ mkdir build
$ cd build

$ cmake ..

-- The C compiler identification is GNU 4.4.7
-- The CXX compiler identification is GNU 4.4.7
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
Boost  found.
Found Boost components:
   graph;program_options;system;filesystem
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Sparsehash: /usr/local/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /projects/home/paudano3/temp/gam-ngs/build

$ make

Scanning dependencies of target BamTools
[  1%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/BamAlignment.cpp.o
[  2%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/BamMultiReader.cpp.o 
[  3%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/BamReader.cpp.o  
[  5%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/BamWriter.cpp.o  
[  6%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/SamHeader.cpp.o  
[  7%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/SamProgram.cpp.o  
[  8%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/SamProgramChain.cpp.o
[ 10%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/SamReadGroup.cpp.o  
[ 11%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/SamReadGroupDictionary.cpp.o  
[ 12%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/SamSequence.cpp.o  
[ 13%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/SamSequenceDictionary.cpp.o  
[ 15%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/bam/BamHeader_p.cpp.o  
[ 16%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/bam/BamMultiReader_p.cpp.o  
[ 17%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/bam/BamRandomAccessController_p.cpp.o  
[ 18%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/bam/BamReader_p.cpp.o  
[ 20%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/bam/BamWriter_p.cpp.o  
[ 21%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/index/BamIndexFactory_p.cpp.o  
[ 22%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/index/BamStandardIndex_p.cpp.o  
[ 23%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/index/BamToolsIndex_p.cpp.o  
[ 25%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/BamDeviceFactory_p.cpp.o  
[ 26%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/BamFile_p.cpp.o
[ 27%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/BamFtp_p.cpp.o
[ 28%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/BamHttp_p.cpp.o
[ 30%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/BamPipe_p.cpp.o
[ 31%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/BgzfStream_p.cpp.o
[ 32%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/ByteArray_p.cpp.o
[ 33%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/HostAddress_p.cpp.o
[ 35%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/HostInfo_p.cpp.o
[ 36%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/HttpHeader_p.cpp.o
[ 37%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/ILocalIODevice_p.cpp.o
[ 38%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/RollingBuffer_p.cpp.o
[ 40%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocket_p.cpp.o
[ 41%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_p.cpp.o
[ 42%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/io/TcpSocketEngine_unix_p.cpp.o
[ 43%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatParser_p.cpp.o
[ 45%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/sam/SamFormatPrinter_p.cpp.o
[ 46%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/sam/SamHeaderValidator_p.cpp.o
[ 47%] Building CXX object lib/bamtools-2.3.0/src/api/CMakeFiles/BamTools.dir/internal/utils/BamException_p.cpp.o
Linking CXX static library libbamtools.a
[ 47%] Built target BamTools
Scanning dependencies of target gam-create
[ 48%] Building CXX object CMakeFiles/gam-create.dir/src/gam-create.cc.o
[ 50%] Building CXX object CMakeFiles/gam-create.dir/src/CreateBlocks.cc.o
[ 51%] Building CXX object CMakeFiles/gam-create.dir/src/Options.cc.o
[ 52%] Building CXX object CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o
[ 53%] Building CXX object CMakeFiles/gam-create.dir/lib/src/assembly/Read.cc.o
[ 55%] Building CXX object CMakeFiles/gam-create.dir/lib/src/assembly/Frame.cc.o
[ 56%] Building CXX object CMakeFiles/gam-create.dir/lib/src/assembly/Block.cc.o
[ 57%] Building CXX object CMakeFiles/gam-create.dir/lib/src/bam/MultiBamReader.cc.o
[ 58%] Building CXX object CMakeFiles/gam-create.dir/lib/src/UtilityFunctions.cc.o
make[2]: **\* No rule to make target `/usr/lib64/lib64/libboost_graph-mt.so.5', needed by`../bin/gam-create'.  Stop.
make[1]: **\* [CMakeFiles/gam-create.dir/all] Error 2
make: **\* [all] Error 2

Host information:
Red Hat Enterprise Linux Server release 6.6 (Santiago)

Linux XXX 2.6.32-504.1.3.el6.x86_64 #1 SMP Fri Oct 31 11:37:10 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux

System packages were recently updated.

**Comment by jtremblay** [comment]
You guys found a fix for this. I'm having the same issue here...

**Comment by paudano** [comment]
No fix yet. I messaged the developer about it yesterday. If I get a fix that is not also posted here, I will be sure to update this thread.

**Comment by jtremblay** [comment]
Got it to work by cmaking with this command:
cmake -DBoost_NO_BOOST_CMAKE=TRUE ../ 
"If Boost was built using the boost-cmake project it provides a package configuration file for use with find_package’s Config mode. This module looks for the package configuration file called BoostConfig.cmake or boost-config.cmake and stores the result in cache entry “Boost_DIR”. If found, the package configuration file is loaded and this module returns with no further action. See documentation of the Boost CMake package configuration for details on what it provides."

then run make. But then it crashes further down the road:
collect2: ld returned 1 exit status
make[2]: **\* [../bin/gam-create] Error 1
make[1]: **\* [CMakeFiles/gam-create.dir/all] Error 2
make: **\* [all] Error 2

...Always had bad experiences with cmake...

**Comment by jtremblay** [comment]
Solved. I ended up installing Boost 1.44.0, sparsehash 2.0.2 and cmake 2.8.5. Very important, when you install boost, don't forget to put those two options:  --threading=multi --layout=tagged

#First bootstrap.
./bootstrap.sh
#Then 
./bjam install --prefix=/path/to/your/installation --threading=multi --layout=tagged

Then install gam-ngs with provided instructions with cmake...
Should work.

**Comment by paudano** [comment]
jtremblay solved.
