### ISSUE TITLE
Compilation Error during make

### ISSUE THREAD

**Issue by FatenNasuha10** [vice87/gam-ngs#6]
Hello.

I have been having problems installing the GAM-NGS software on Fedora 17 . During 'make', error appear : 

$make

Linking CXX executable ../bin/gam-create
CMakeFiles/gam-create.dir/src/gam-create.cc.o: In function `global constructors keyed to g_options':
gam-create.cc:(.text+0x23): undefined reference to`boost::system::generic_category()'
gam-create.cc:(.text+0x2f): undefined reference to `boost::system::generic_category()'
gam-create.cc:(.text+0x3b): undefined reference to`boost::system::system_category()'
CMakeFiles/gam-create.dir/src/CreateBlocks.cc.o: In function `global constructors keyed to _ZN7modules12CreateBlocks7executeEv':
CreateBlocks.cc:(.text+0x23): undefined reference to`boost::system::generic_category()'
CreateBlocks.cc:(.text+0x2f): undefined reference to `boost::system::generic_category()'
CreateBlocks.cc:(.text+0x3b): undefined reference to`boost::system::system_category()'
CMakeFiles/gam-create.dir/src/CreateBlocks.cc.o: In function `modules::CreateBlocks::execute()':
CreateBlocks.cc:(.text+0x4c5): undefined reference to`boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code_)'
CreateBlocks.cc:(.text+0x56f): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code_)'
CreateBlocks.cc:(.text+0x6ad): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)'
CreateBlocks.cc:(.text+0x772): undefined reference to`boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code_)'
CreateBlocks.cc:(.text+0x78d): undefined reference to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code_)'
CMakeFiles/gam-create.dir/src/CreateBlocks.cc.o:CreateBlocks.cc:(.text+0x107f): more undefined references to `boost::filesystem::detail::status(boost::filesystem::path const&, boost::system::error_code*)' follow
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o: In function`_ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKSsS4_i.clone.4':
OptionsCreate.cc:(.text+0xba): undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
OptionsCreate.cc:(.text+0xce): undefined reference to`boost::program_options::error_with_option_name::error_with_option_name(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o: In function `options::OptionsCreate::process(int, char**)':
OptionsCreate.cc:(.text+0x308): undefined reference to`boost::program_options::options_description::options_description(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o: In function `boost::program_options::error_with_option_name::~error_with_option_name()':
OptionsCreate.cc:(.text._ZN5boost15program_options22error_with_option_nameD2Ev[_ZN5boost15program_options22error_with_option_nameD5Ev]+0x19): undefined reference to`vtable for boost::program_options::error_with_option_name'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error const&)':
OptionsCreate.cc:(.text._ZN5boost15program_options16validation_errorC2ERKS1_[_ZN5boost15program_options16validation_errorC5ERKS1_]+0x38): undefined reference to `vtable for boost::program_options::error_with_option_name'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o: In function`boost::program_options::basic_command_line_parser<char>::run()':
OptionsCreate.cc:(.text._ZN5boost15program_options25basic_command_line_parserIcE3runEv[boost::program_options::basic_command_line_parser<char>::run()]+0x18): undefined reference to `boost::program_options::detail::cmdline::get_canonical_option_prefix()'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost15program_options16validation_errorE[vtable for boost::program_options::validation_error]+0x20): undefined reference to`boost::program_options::error_with_option_name::what() const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost15program_options16validation_errorE[vtable for boost::program_options::validation_error]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTIN5boost15program_options16validation_errorE[typeinfo for boost::program_options::validation_error]+0x10): undefined reference to`typeinfo for boost::program_options::error_with_option_name'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[vtable for boost::exception_detail::error_info_injectorboost::program_options::validation_error]+0x20): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[vtable for boost::exception_detail::error_info_injector<boost::program_options::validation_error>]+0x30): undefined reference to`boost::program_options::error_with_option_name::substitute_placeholders(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[vtable for boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::program_options::validation_error >]+0x28): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::validation_error> >]+0x38): undefined reference to`boost::program_options::error_with_option_name::substitute_placeholders(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[vtable for boost::exception_detail::error_info_injectorboost::program_options::invalid_option_value]+0x20): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[vtable for boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value>]+0x30): undefined reference to`boost::program_options::error_with_option_name::substitute_placeholders(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[vtable for boost::program_options::invalid_option_value]+0x20): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost15program_options20invalid_option_valueE[vtable for boost::program_options::invalid_option_value]+0x30): undefined reference to`boost::program_options::error_with_option_name::substitute_placeholders(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[vtable for boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::program_options::invalid_option_value >]+0x28): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/gam-create.dir/src/OptionsCreate.cc.o:(.rodata._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[vtable for boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value> >]+0x38): undefined reference to`boost::program_options::error_with_option_name::substitute_placeholders(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
collect2: ld returned 1 exit status
make[2]: **\* [../bin/gam-create] Error 1
make[1]: **\* [CMakeFiles/gam-create.dir/all] Error 2
make: **\* [all] Error 2

Currently using boost_1_54_0, cmake-2.8.11.1, zlib-1.2.8, sparsehash-2.0.2.

Hope you can help me. Thank you.

**Comment by vice87** [comment]
Which version of gcc are you using? I suggest you to use at least version 4.4 (also 4.3 should work but I'm not completely sure about it). However, previous versions should not be able to compile the tool.

**Comment by FatenNasuha10** [comment]
Thank you for your reply. I'm currently using gcc 4.4.6 (Red Hat).

**Comment by vice87** [comment]
Then compiler's version should not be the problem.
One more question: are you sure that boost-system, boost-filesystem and boost-program-options component have been installed? What is the output of the cmake command?

**Comment by FatenNasuha10** [comment]
The output for the cmake command : 

Boost found.
Found Boost components:
     graph;program_option;system;filesystem

Found Sparsehash include at: /usr/local/include.

--Found SPARSEHASH in /usr/local/include
--Configuration done
--Generating done
--Build files have been written to: /home/faten/new/gam-ngs-master/build

**Comment by vice87** [comment]
It seems that there is a problem in linking boost libraries but I've no clue how to solve it.
In the system you're using, is the version 1.54.0 the only one or are there other boost versions installed?

The only thing that I can suggest you now is the following (and I'm not sure it will work).
In the file CMakeLists.txt try to replace 

```
target_link_libraries(gam-create ${Boost_LIBRARIES})
```

which can be found at line 79 with the following line

```
target_link_libraries(gam-create ${Boost_PROGRAM_OPTIONS_LIBRARIES} ${Boost_FILESYSTEM_LIBRARIES}  ${Boost_SYSTEM_LIBRARIES} ${Boost_GRAPH_LIBRARIES})
```

and also replace

```
target_link_libraries(gam-merge ${Boost_LIBRARIES})
```

at line 87 with the following line

```
target_link_libraries(gam-merge ${Boost_PROGRAM_OPTIONS_LIBRARIES} ${Boost_FILESYSTEM_LIBRARIES}  ${Boost_SYSTEM_LIBRARIES} ${Boost_GRAPH_LIBRARIES})
```

**Comment by FatenNasuha10** [comment]
I will check back my boost version and try to replace the CMakeLists.txt.

Hopefully it will solved it. 

Thank you so much.
